import JSZip from 'jszip'
import { ENGINE_SOURCES } from './engineSources.js'

function createComponentConfig(state) {
  const config = {
    modelFileName: state.model?.name ?? null,
    effectOptions: {
      colors: state.colors,
      pixelSize: state.pixelSize,
      ditherType: state.ditherType,
      invert: state.invert,
      minBrightness: state.minBrightness,
      backgroundColor: state.backgroundColor,
      animationDuration: state.animationDuration,
      fadeVariant: state.fadeVariant
    },
    useFadeInOut: state.useFadeInOut,
    animationEffects: state.animationEffects,
    animationSpeed: state.animationSpeed,
    showPhaseDuration: state.showPhaseDuration,
    lightDirection: state.lightDirection,
    baseRotation: state.baseRotation,
    rotateOnShow: state.rotateOnShow,
    showPreset: state.showPreset
  }
  return `export const config = ${JSON.stringify(config, null, 2)}\n`
}

function generateIndexJsx(componentName, modelFileName) {
  // Model load block: new URL path must be a static string literal (not a template variable)
  // so bundlers (Vite, webpack 5) can statically analyze the asset reference.
  // The generator inserts the literal filename at code-gen time.
  const modelBlock = modelFileName
    ? `
    // Load model — static URL literal required for Vite/webpack asset handling
    const modelUrl = new URL('./assets/${modelFileName}', import.meta.url)
    fetch(modelUrl)
      .then(res => { if (!res.ok) throw new Error('Failed to load model'); return res.blob() })
      .then(blob => new File([blob], config.modelFileName))
      .then(file => { if (managerRef.current) manager.loadModel(file) })`
    : ''

  return `import { useEffect, useRef } from 'react'
import { SceneManager } from './engine/SceneManager.js'
import { config } from './config.js'

/**
 * Drop-in React component generated by BitmapForge.
 * Peer dependency: three (>=0.150.0)
 * Works with Vite and webpack 5.
 */
export default function ${componentName}({ className, style }) {
  const containerRef = useRef(null)
  // StrictMode guard: prevents double-init in React 19 dev mode
  const managerRef = useRef(null)

  useEffect(() => {
    if (managerRef.current) return
    const container = containerRef.current
    if (!container) return

    const manager = new SceneManager(container, config.effectOptions)
    managerRef.current = manager

    // rAF avoids measuring 0×0 before the browser has laid out the container
    requestAnimationFrame(() => {
      if (!managerRef.current) return
      manager.setSize(container.clientWidth, container.clientHeight)
    })
${modelBlock}
    manager.updateAnimationOptions({
      useFadeInOut: config.useFadeInOut,
      animationEffects: config.animationEffects,
      animationSpeed: config.animationSpeed,
      showPhaseDuration: config.showPhaseDuration,
      animationDuration: config.animationDuration,
      rotateOnShow: config.rotateOnShow,
      showPreset: config.showPreset
    })
    manager.setLightDirection(config.lightDirection.x, config.lightDirection.y, config.lightDirection.z)
    manager.setBaseRotation(config.baseRotation.x, config.baseRotation.y, config.baseRotation.z)

    const ro = new ResizeObserver(() => {
      manager.setSize(container.clientWidth, container.clientHeight)
    })
    ro.observe(container)

    return () => {
      ro.disconnect()
      managerRef.current?.destroy()
      managerRef.current = null
    }
  }, [])

  return <div ref={containerRef} className={className} style={style} />
}
`
}

function generateReactReadme(componentName) {
  return `# ${componentName}

BitmapForge React component — drop this folder into your project.

## Requirements

- React 18+
- \`three\` installed in your project (\`npm install three\`)
- Vite or webpack 5 (for \`new URL\` asset handling)

## Usage

\`\`\`jsx
import ${componentName} from './${componentName}'

function App() {
  return <${componentName} style={{ width: 300, height: 300 }} />
}
\`\`\`

## Notes

- **Browser only** — requires WebGL. Do not render server-side.
- The component is self-contained. The \`engine/\` folder is vendored; no separate install needed.
- To update settings, re-export from BitmapForge and replace this folder.
`
}

async function buildReactComponent(state, componentName = 'MyAnimation') {
  const zip = new JSZip()
  const root = zip.folder(componentName)
  const modelFileName = state.model?.name ?? null

  root.file('index.jsx', generateIndexJsx(componentName, modelFileName))
  root.file('config.js', createComponentConfig(state))
  root.file('README.md', generateReactReadme(componentName))

  for (const { path, content } of ENGINE_SOURCES) {
    root.file(path, content)
  }

  if (state.model?.file) {
    root.file(`assets/${state.model.name}`, state.model.file)
  }

  return zip.generateAsync({ type: 'blob' })
}

export { buildReactComponent }
